modLoader = "javafml"
loaderVersion = "[43,)"

license = "DBaJ"
issueTrackerURL="https://github.com/BRForgers/Ducts/issues"

[[mods]]
modId = "ducts"
version = "${file.jarVersion}"
displayName = "Ducts"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ducts"
logoFile= "icon.png"
authors = "BRForgers, armelin1"
description = '''
This mod add ducts.
'''

[[dependencies.ducts]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ducts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
